### ISSUE TITLE
[Bug] When connected to the wrong chain, the mint username button gets stuck

### ISSUE THREAD

**Issue by KorbinianK** [iggy-social/tko-chat#1]
**Observed behavior**
The "mint username" button is active as soon as you connect your wallet, even when connected to another chain. Clicking it puts the button in the loading state, but nothing happens.

**Expected behaviour**
When connected to an unsupported chain, the button should be disabled

**Steps to reproduce:**
- Connect to an unsupported chain in Metamask
- Connect your wallet to the dapp
- Enter a new username
- click "mint username"

**Comment by tempe-techie** [comment]
Fixed.
